### ISSUE TITLE
Soundcloud example comments in the code

### ISSUE THREAD

**Issue by ajsb85** [matthew-carroll/fluttery_audio#12]
Dear @matthew-carroll 
Can I use this library to reproduce from soundcloud stream audio?

**Comment by hulastone** [comment]
i think it ok.

**Comment by FleurA** [comment]
Hey, 
I am trying to load other mp3 files, but unfortunetly soundcloud disabled new users, so i can not use their streaming api. I have tried dropbox, drive, soundclick (all of which have their own mediaplayer, and in browser they immediatly start playing) but it does not work if I try to load them. I get: D/FlutteryAudioPlugin(28722): Loading new audio.
D/AudioPlayer(28722): load()
V/MediaPlayer(28722): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer(28722): cleanDrmObj: mDrmObj=null mDrmSessionId=null
V/MediaHTTPService(28722): MediaHTTPService(android.media.MediaHTTPService@10ce01f): Cookies: null
D/FlutteryAudioPlugin(28722): Android -> Flutter: onAudioLoading()
V/MediaHTTPService(28722): makeHTTPConnection: CookieHandler (java.net.CookieManager@4bfa723) exists.
V/MediaHTTPService(28722): makeHTTPConnection(android.media.MediaHTTPService@10ce01f): cookieHandler: java.net.CookieManager@4bfa723 Cookies: null
E/MediaPlayerNative(28722): error (1, -2147483648)
E/MediaPlayer(28722): Error (1,-2147483648)
W/AudioPlayer(28722): onError()


and after a few seconds, it loads the next song (which are the original soundcloud examples)

**Comment by suburbanworrier** [comment]
@FleurA 
swap out the contents of audio_samples.dart to your desired list of remote mp3 files:
```dart
final audioUrls = [
  "https://archive.org/download/TheChroniclesOfNarnia-PrinceCaspianByCSLewis/1%20-%20Prince%20Caspian%20by%20C%20S%20Lewis%20.mp3",
  "https://archive.org/download/TheChroniclesOfNarnia-PrinceCaspianByCSLewis/2%20-%20Prince%20Caspian%20by%20C%20S%20Lewis%20.mp3",
  "https://archive.org/download/TheChroniclesOfNarnia-PrinceCaspianByCSLewis/3%20-%20Prince%20Caspian%20by%20C%20S%20Lewis%20.mp3",
  "https://archive.org/download/TheChroniclesOfNarnia-PrinceCaspianByCSLewis/4%20-%20Prince%20Caspian%20by%20C%20S%20Lewis%20.mp3"
];
```
It really doesn't matter to the player what the source is - as long as they're accessible.
Archive.org has a huge collection of mp3s you can use freely.
HTH

**Comment by suburbanworrier** [comment]
@ajsb85 The urls used in the example code contain Mr Carroll's SoundCloud API credentials (or at least they contain *somebody's* credentials.

If you've already got your own API credentials just update the list items in audioUrls with your `secret_token` and `client_id` values.

As @FleurA notes SoundCloud aren't currently releasing new API keys http://soundcloud.com/you/apps/new

**Comment by suburbanworrier** [comment]
@ajsb85 if your issue is resolved please mark it as solved or closed or whatever fits/is available to you.
It'll help let the developer focus on the real tasks. :)

**Comment by suburbanworrier** [comment]
@ajsb85 Thanks for the thumbs up. As the Issue opener you should see a `Close Issue` button next to the green `Comment` button at the bottom of the screen.
HTH
