### ISSUE TITLE
Feature request: Build in AndroidX support

### ISSUE THREAD

**Issue by Kwasow** [matthew-carroll/fluttery_audio#19]
This plugin does not support AndroidX and when compiling an app using AndroidX gives the following error:

`package android.support.annotation.NonNull does not exist`

As a workaround you can change the line
`import android.support.annotation.NonNull;`
to
`import androidx.annotation.NonNull;`
in the following files in the direcotry `$HOME/.pub-cache/hosted/pub.dartlang.org/fluttery_audio-0.0.4/android/src/main/java/io/fluttery/flutteryaudio/`:

- AudioPlayer.java (line 6)
- AudioVisualizer.java (line 5)
- FlutteryAudioPlugin.java (line 5)

**Comment by suburbanworrier** [comment]
@Kwasow this looks very much like #11 which is awaiting action from the owner.
I'm therefore not sure this issue adds any value to the project.

**Comment by Kwasow** [comment]
Seems to be the same. Then I'll just leave it as a walk-around tutorial. Closing thread.
